### ISSUE TITLE
Bass notes of Weimar jazz dataset ? 

### ISSUE THREAD

**Issue by jjazzboss** [jakobabesser/walking_bass_transcription_dnn#2]
Thanks for this interesting work.

> This algorithm was used to create the beat-wise bass pitch values included in the Weimar Jazz Database
> http://jazzomat.hfm-weimar.de/dbformat/dboverview.html

Does it mean a walking bass dataset was built from the Weimar jazz audio dataset ? I could not find it on this link, the Midi files only contain the solo notes...  Any help is appreciated.

**Comment by jakobabesser** [comment]
Hi @jjazzboss, as detailed in https://pdfs.semanticscholar.org/6037/ec4cedce9198b7f795f7ae7b75a7b3218f93.pdf, we followed a semi-supervised process. We started with 40 tracks of the WJD, for which a musicologist annotated beat-level bass pitches. The dataset was not published though.

**Comment by jjazzboss** [comment]
ok, too bad
